### ISSUE TITLE
Multi Alert Doesn't work

### ISSUE THREAD

**Issue by Infinitism** [themeteorchef/bert#42] opened 2017-01-11 03:43 UTC
Hi, 

When I was trying to use Bert to display several error messages at once called inside a foreach of an array of error messages and only the last array item seems to be created and messages don't seem to stack on top of eachother.

**Comment by themeteorchef** [comment] 2017-01-11 17:57
Hi @Infinitism, at the moment Bert doesn't support stacking. The new messages just swap out. Flagging this as a possible feature but going to close it out as it's not a bug with the current API.

**Closed as completed by themeteorchef** 2017-01-11 17:57 UTC
Labels: feature
